//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaminServices
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaminServices.ParaclinicWebServiceSoap")]
    public interface ParaclinicWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Diagnose_par", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TaminServices.Result_Para> Save_Diagnose_parAsync(TaminServices.ParaUserInfo ParaUInfo, long sRequestId, TaminServices.Diagnose Diagno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Session_physio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TaminServices.Result_Para> Save_Session_physioAsync(TaminServices.ParaUserInfo ParaUInfo, long sRequestId, TaminServices.Save_Session_physioSParList sParList, string sParListJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TaminServices.Result_Para> Save_RequestAsync(TaminServices.ParaUserInfo ParaUInfo, TaminServices.DoctorInfo DocInfo, TaminServices.PrescInfo PrcInfo, TaminServices.LabPrescInfo LabPrscInfo, TaminServices.PhysioPrescInfo PhyPrscInfo, TaminServices.PrescDInfo[] PrescDInfo);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Request_Eprsc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TaminServices.Save_Request_EprscResponse> Save_Request_EprscAsync(TaminServices.Save_Request_EprscRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Request_Eprsc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TaminServices.Result_Para> Delete_Request_EprscAsync(TaminServices.ParaUserInfo ParaUInfo, TaminServices.EPrescInfo EPrcInfo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ParaUserInfo
    {
        
        private string userIDField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EPrescInfo
    {
        
        private string mobileField;
        
        private string parTypeField;
        
        private string cust_Service_typeField;
        
        private string is2KField;
        
        private string docFani_IDField;
        
        private long note_head_eprsc_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ParType
        {
            get
            {
                return this.parTypeField;
            }
            set
            {
                this.parTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cust_Service_type
        {
            get
            {
                return this.cust_Service_typeField;
            }
            set
            {
                this.cust_Service_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Is2K
        {
            get
            {
                return this.is2KField;
            }
            set
            {
                this.is2KField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DocFani_ID
        {
            get
            {
                return this.docFani_IDField;
            }
            set
            {
                this.docFani_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long note_head_eprsc_id
        {
            get
            {
                return this.note_head_eprsc_idField;
            }
            set
            {
                this.note_head_eprsc_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrescDInfo
    {
        
        private string tAREFCODEField;
        
        private int numField;
        
        private long note_details_eprsc_idField;
        
        private int item_PriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TAREFCODE
        {
            get
            {
                return this.tAREFCODEField;
            }
            set
            {
                this.tAREFCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Num
        {
            get
            {
                return this.numField;
            }
            set
            {
                this.numField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long note_details_eprsc_id
        {
            get
            {
                return this.note_details_eprsc_idField;
            }
            set
            {
                this.note_details_eprsc_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Item_Price
        {
            get
            {
                return this.item_PriceField;
            }
            set
            {
                this.item_PriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhysioPrescInfo
    {
        
        private int totalSessionField;
        
        private int organNoField;
        
        private string physioDiagnoseCodeField;
        
        private string physioDiagnoseCommentField;
        
        private string darmanPhysioField;
        
        private string darmanDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalSession
        {
            get
            {
                return this.totalSessionField;
            }
            set
            {
                this.totalSessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int OrganNo
        {
            get
            {
                return this.organNoField;
            }
            set
            {
                this.organNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhysioDiagnoseCode
        {
            get
            {
                return this.physioDiagnoseCodeField;
            }
            set
            {
                this.physioDiagnoseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PhysioDiagnoseComment
        {
            get
            {
                return this.physioDiagnoseCommentField;
            }
            set
            {
                this.physioDiagnoseCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DarmanPhysio
        {
            get
            {
                return this.darmanPhysioField;
            }
            set
            {
                this.darmanPhysioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DarmanDoc
        {
            get
            {
                return this.darmanDocField;
            }
            set
            {
                this.darmanDocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LabPrescInfo
    {
        
        private string labDiagnoseCodeField;
        
        private string labDiagnoseCommentField;
        
        private string labGrpCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LabDiagnoseCode
        {
            get
            {
                return this.labDiagnoseCodeField;
            }
            set
            {
                this.labDiagnoseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LabDiagnoseComment
        {
            get
            {
                return this.labDiagnoseCommentField;
            }
            set
            {
                this.labDiagnoseCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LabGrpCode
        {
            get
            {
                return this.labGrpCodeField;
            }
            set
            {
                this.labGrpCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrescInfo
    {
        
        private string bletSerialField;
        
        private string mobileField;
        
        private string prescDateField;
        
        private string parTypeField;
        
        private string cust_Service_typeField;
        
        private string bastariField;
        
        private string firstDiagnoseCodeField;
        
        private string is2KField;
        
        private string docFani_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BletSerial
        {
            get
            {
                return this.bletSerialField;
            }
            set
            {
                this.bletSerialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrescDate
        {
            get
            {
                return this.prescDateField;
            }
            set
            {
                this.prescDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ParType
        {
            get
            {
                return this.parTypeField;
            }
            set
            {
                this.parTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Cust_Service_type
        {
            get
            {
                return this.cust_Service_typeField;
            }
            set
            {
                this.cust_Service_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Bastari
        {
            get
            {
                return this.bastariField;
            }
            set
            {
                this.bastariField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FirstDiagnoseCode
        {
            get
            {
                return this.firstDiagnoseCodeField;
            }
            set
            {
                this.firstDiagnoseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Is2K
        {
            get
            {
                return this.is2KField;
            }
            set
            {
                this.is2KField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DocFani_ID
        {
            get
            {
                return this.docFani_IDField;
            }
            set
            {
                this.docFani_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DoctorInfo
    {
        
        private string dOCIDField;
        
        private string dOC_SPECField;
        
        private string dOC_FNAMEField;
        
        private string dOC_LNAMEField;
        
        private string dOC_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DOCID
        {
            get
            {
                return this.dOCIDField;
            }
            set
            {
                this.dOCIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DOC_SPEC
        {
            get
            {
                return this.dOC_SPECField;
            }
            set
            {
                this.dOC_SPECField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DOC_FNAME
        {
            get
            {
                return this.dOC_FNAMEField;
            }
            set
            {
                this.dOC_FNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DOC_LNAME
        {
            get
            {
                return this.dOC_LNAMEField;
            }
            set
            {
                this.dOC_LNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DOC_TYPE
        {
            get
            {
                return this.dOC_TYPEField;
            }
            set
            {
                this.dOC_TYPEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result_Para
    {
        
        private string errorMessageField;
        
        private long requestIdField;
        
        private int rCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RCode
        {
            get
            {
                return this.rCodeField;
            }
            set
            {
                this.rCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Diagnose
    {
        
        private bool isNormalField;
        
        private string diagnoseCommentField;
        
        private string docFani_IDField;
        
        private string[] lstDiagnoseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsNormal
        {
            get
            {
                return this.isNormalField;
            }
            set
            {
                this.isNormalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DiagnoseComment
        {
            get
            {
                return this.diagnoseCommentField;
            }
            set
            {
                this.diagnoseCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocFani_ID
        {
            get
            {
                return this.docFani_IDField;
            }
            set
            {
                this.docFani_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] lstDiagnoseCode
        {
            get
            {
                return this.lstDiagnoseCodeField;
            }
            set
            {
                this.lstDiagnoseCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class Save_Session_physioSParList
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_Request_Eprsc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_Request_EprscRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TaminServices.ParaUserInfo ParaUInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public TaminServices.EPrescInfo EPrcInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public TaminServices.LabPrescInfo LabPrscInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public TaminServices.PhysioPrescInfo PhyPrscInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public TaminServices.PrescDInfo[] PrescDInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string logMessage;
        
        public Save_Request_EprscRequest()
        {
        }
        
        public Save_Request_EprscRequest(TaminServices.ParaUserInfo ParaUInfo, TaminServices.EPrescInfo EPrcInfo, TaminServices.LabPrescInfo LabPrscInfo, TaminServices.PhysioPrescInfo PhyPrscInfo, TaminServices.PrescDInfo[] PrescDInfo, string logMessage)
        {
            this.ParaUInfo = ParaUInfo;
            this.EPrcInfo = EPrcInfo;
            this.LabPrscInfo = LabPrscInfo;
            this.PhyPrscInfo = PhyPrscInfo;
            this.PrescDInfo = PrescDInfo;
            this.logMessage = logMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_Request_EprscResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_Request_EprscResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TaminServices.Result_Para Save_Request_EprscResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string logMessage;
        
        public Save_Request_EprscResponse()
        {
        }
        
        public Save_Request_EprscResponse(TaminServices.Result_Para Save_Request_EprscResult, string logMessage)
        {
            this.Save_Request_EprscResult = Save_Request_EprscResult;
            this.logMessage = logMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ParaclinicWebServiceSoapChannel : TaminServices.ParaclinicWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ParaclinicWebServiceSoapClient : System.ServiceModel.ClientBase<TaminServices.ParaclinicWebServiceSoap>, TaminServices.ParaclinicWebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ParaclinicWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ParaclinicWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ParaclinicWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParaclinicWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ParaclinicWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParaclinicWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ParaclinicWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParaclinicWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TaminServices.Result_Para> Save_Diagnose_parAsync(TaminServices.ParaUserInfo ParaUInfo, long sRequestId, TaminServices.Diagnose Diagno)
        {
            return base.Channel.Save_Diagnose_parAsync(ParaUInfo, sRequestId, Diagno);
        }
        
        public System.Threading.Tasks.Task<TaminServices.Result_Para> Save_Session_physioAsync(TaminServices.ParaUserInfo ParaUInfo, long sRequestId, TaminServices.Save_Session_physioSParList sParList, string sParListJson)
        {
            return base.Channel.Save_Session_physioAsync(ParaUInfo, sRequestId, sParList, sParListJson);
        }
        
        public System.Threading.Tasks.Task<TaminServices.Result_Para> Save_RequestAsync(TaminServices.ParaUserInfo ParaUInfo, TaminServices.DoctorInfo DocInfo, TaminServices.PrescInfo PrcInfo, TaminServices.LabPrescInfo LabPrscInfo, TaminServices.PhysioPrescInfo PhyPrscInfo, TaminServices.PrescDInfo[] PrescDInfo)
        {
            return base.Channel.Save_RequestAsync(ParaUInfo, DocInfo, PrcInfo, LabPrscInfo, PhyPrscInfo, PrescDInfo);
        }
        
        public System.Threading.Tasks.Task<TaminServices.Save_Request_EprscResponse> Save_Request_EprscAsync(TaminServices.Save_Request_EprscRequest request)
        {
            return base.Channel.Save_Request_EprscAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaminServices.Result_Para> Delete_Request_EprscAsync(TaminServices.ParaUserInfo ParaUInfo, TaminServices.EPrescInfo EPrcInfo)
        {
            return base.Channel.Delete_Request_EprscAsync(ParaUInfo, EPrcInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ParaclinicWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ParaclinicWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ParaclinicWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://darmanws.tamin.ir/ParaclinicWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ParaclinicWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://darmanws.tamin.ir/ParaclinicWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ParaclinicWebServiceSoap,
            
            ParaclinicWebServiceSoap12,
        }
    }
}
