//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParTest4.TaminServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaminServices.ParaclinicWebServiceSoap")]
    public interface ParaclinicWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Diagnose_par", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParTest4.TaminServices.Result_Para Save_Diagnose_par(ParTest4.TaminServices.ParaUserInfo ParaUInfo, long sRequestId, ParTest4.TaminServices.Diagnose Diagno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Diagnose_par", ReplyAction="*")]
        System.Threading.Tasks.Task<ParTest4.TaminServices.Result_Para> Save_Diagnose_parAsync(ParTest4.TaminServices.ParaUserInfo ParaUInfo, long sRequestId, ParTest4.TaminServices.Diagnose Diagno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Session_physio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParTest4.TaminServices.Result_Para Save_Session_physio(ParTest4.TaminServices.ParaUserInfo ParaUInfo, long sRequestId, System.Data.DataTable sParList, string sParListJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Session_physio", ReplyAction="*")]
        System.Threading.Tasks.Task<ParTest4.TaminServices.Result_Para> Save_Session_physioAsync(ParTest4.TaminServices.ParaUserInfo ParaUInfo, long sRequestId, System.Data.DataTable sParList, string sParListJson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Request", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParTest4.TaminServices.Result_Para Save_Request(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.DoctorInfo DocInfo, ParTest4.TaminServices.PrescInfo PrcInfo, ParTest4.TaminServices.LabPrescInfo LabPrscInfo, ParTest4.TaminServices.PhysioPrescInfo PhyPrscInfo, ParTest4.TaminServices.PrescDInfo[] PrescDInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Request", ReplyAction="*")]
        System.Threading.Tasks.Task<ParTest4.TaminServices.Result_Para> Save_RequestAsync(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.DoctorInfo DocInfo, ParTest4.TaminServices.PrescInfo PrcInfo, ParTest4.TaminServices.LabPrescInfo LabPrscInfo, ParTest4.TaminServices.PhysioPrescInfo PhyPrscInfo, ParTest4.TaminServices.PrescDInfo[] PrescDInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Request_Eprsc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParTest4.TaminServices.Save_Request_EprscResponse Save_Request_Eprsc(ParTest4.TaminServices.Save_Request_EprscRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save_Request_Eprsc", ReplyAction="*")]
        System.Threading.Tasks.Task<ParTest4.TaminServices.Save_Request_EprscResponse> Save_Request_EprscAsync(ParTest4.TaminServices.Save_Request_EprscRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Request_Eprsc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ParTest4.TaminServices.Result_Para Delete_Request_Eprsc(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.EPrescInfo EPrcInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Request_Eprsc", ReplyAction="*")]
        System.Threading.Tasks.Task<ParTest4.TaminServices.Result_Para> Delete_Request_EprscAsync(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.EPrescInfo EPrcInfo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ParaUserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EPrescInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mobileField;
        
        private string parTypeField;
        
        private string cust_Service_typeField;
        
        private string is2KField;
        
        private string docFani_IDField;
        
        private long note_head_eprsc_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ParType {
            get {
                return this.parTypeField;
            }
            set {
                this.parTypeField = value;
                this.RaisePropertyChanged("ParType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Cust_Service_type {
            get {
                return this.cust_Service_typeField;
            }
            set {
                this.cust_Service_typeField = value;
                this.RaisePropertyChanged("Cust_Service_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Is2K {
            get {
                return this.is2KField;
            }
            set {
                this.is2KField = value;
                this.RaisePropertyChanged("Is2K");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DocFani_ID {
            get {
                return this.docFani_IDField;
            }
            set {
                this.docFani_IDField = value;
                this.RaisePropertyChanged("DocFani_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long note_head_eprsc_id {
            get {
                return this.note_head_eprsc_idField;
            }
            set {
                this.note_head_eprsc_idField = value;
                this.RaisePropertyChanged("note_head_eprsc_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrescDInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tAREFCODEField;
        
        private int numField;
        
        private long note_details_eprsc_idField;
        
        private int item_PriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TAREFCODE {
            get {
                return this.tAREFCODEField;
            }
            set {
                this.tAREFCODEField = value;
                this.RaisePropertyChanged("TAREFCODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
                this.RaisePropertyChanged("Num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long note_details_eprsc_id {
            get {
                return this.note_details_eprsc_idField;
            }
            set {
                this.note_details_eprsc_idField = value;
                this.RaisePropertyChanged("note_details_eprsc_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Item_Price {
            get {
                return this.item_PriceField;
            }
            set {
                this.item_PriceField = value;
                this.RaisePropertyChanged("Item_Price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PhysioPrescInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalSessionField;
        
        private int organNoField;
        
        private string physioDiagnoseCodeField;
        
        private string physioDiagnoseCommentField;
        
        private string darmanPhysioField;
        
        private string darmanDocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalSession {
            get {
                return this.totalSessionField;
            }
            set {
                this.totalSessionField = value;
                this.RaisePropertyChanged("TotalSession");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int OrganNo {
            get {
                return this.organNoField;
            }
            set {
                this.organNoField = value;
                this.RaisePropertyChanged("OrganNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhysioDiagnoseCode {
            get {
                return this.physioDiagnoseCodeField;
            }
            set {
                this.physioDiagnoseCodeField = value;
                this.RaisePropertyChanged("PhysioDiagnoseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PhysioDiagnoseComment {
            get {
                return this.physioDiagnoseCommentField;
            }
            set {
                this.physioDiagnoseCommentField = value;
                this.RaisePropertyChanged("PhysioDiagnoseComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DarmanPhysio {
            get {
                return this.darmanPhysioField;
            }
            set {
                this.darmanPhysioField = value;
                this.RaisePropertyChanged("DarmanPhysio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DarmanDoc {
            get {
                return this.darmanDocField;
            }
            set {
                this.darmanDocField = value;
                this.RaisePropertyChanged("DarmanDoc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LabPrescInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string labDiagnoseCodeField;
        
        private string labDiagnoseCommentField;
        
        private string labGrpCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LabDiagnoseCode {
            get {
                return this.labDiagnoseCodeField;
            }
            set {
                this.labDiagnoseCodeField = value;
                this.RaisePropertyChanged("LabDiagnoseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LabDiagnoseComment {
            get {
                return this.labDiagnoseCommentField;
            }
            set {
                this.labDiagnoseCommentField = value;
                this.RaisePropertyChanged("LabDiagnoseComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LabGrpCode {
            get {
                return this.labGrpCodeField;
            }
            set {
                this.labGrpCodeField = value;
                this.RaisePropertyChanged("LabGrpCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PrescInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bletSerialField;
        
        private string mobileField;
        
        private string prescDateField;
        
        private string parTypeField;
        
        private string cust_Service_typeField;
        
        private string bastariField;
        
        private string firstDiagnoseCodeField;
        
        private string is2KField;
        
        private string docFani_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BletSerial {
            get {
                return this.bletSerialField;
            }
            set {
                this.bletSerialField = value;
                this.RaisePropertyChanged("BletSerial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PrescDate {
            get {
                return this.prescDateField;
            }
            set {
                this.prescDateField = value;
                this.RaisePropertyChanged("PrescDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ParType {
            get {
                return this.parTypeField;
            }
            set {
                this.parTypeField = value;
                this.RaisePropertyChanged("ParType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Cust_Service_type {
            get {
                return this.cust_Service_typeField;
            }
            set {
                this.cust_Service_typeField = value;
                this.RaisePropertyChanged("Cust_Service_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Bastari {
            get {
                return this.bastariField;
            }
            set {
                this.bastariField = value;
                this.RaisePropertyChanged("Bastari");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FirstDiagnoseCode {
            get {
                return this.firstDiagnoseCodeField;
            }
            set {
                this.firstDiagnoseCodeField = value;
                this.RaisePropertyChanged("FirstDiagnoseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Is2K {
            get {
                return this.is2KField;
            }
            set {
                this.is2KField = value;
                this.RaisePropertyChanged("Is2K");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DocFani_ID {
            get {
                return this.docFani_IDField;
            }
            set {
                this.docFani_IDField = value;
                this.RaisePropertyChanged("DocFani_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DoctorInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dOCIDField;
        
        private string dOC_SPECField;
        
        private string dOC_FNAMEField;
        
        private string dOC_LNAMEField;
        
        private string dOC_TYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DOCID {
            get {
                return this.dOCIDField;
            }
            set {
                this.dOCIDField = value;
                this.RaisePropertyChanged("DOCID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DOC_SPEC {
            get {
                return this.dOC_SPECField;
            }
            set {
                this.dOC_SPECField = value;
                this.RaisePropertyChanged("DOC_SPEC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DOC_FNAME {
            get {
                return this.dOC_FNAMEField;
            }
            set {
                this.dOC_FNAMEField = value;
                this.RaisePropertyChanged("DOC_FNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DOC_LNAME {
            get {
                return this.dOC_LNAMEField;
            }
            set {
                this.dOC_LNAMEField = value;
                this.RaisePropertyChanged("DOC_LNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DOC_TYPE {
            get {
                return this.dOC_TYPEField;
            }
            set {
                this.dOC_TYPEField = value;
                this.RaisePropertyChanged("DOC_TYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result_Para : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private long requestIdField;
        
        private int rCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RCode {
            get {
                return this.rCodeField;
            }
            set {
                this.rCodeField = value;
                this.RaisePropertyChanged("RCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Diagnose : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isNormalField;
        
        private string diagnoseCommentField;
        
        private string docFani_IDField;
        
        private string[] lstDiagnoseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsNormal {
            get {
                return this.isNormalField;
            }
            set {
                this.isNormalField = value;
                this.RaisePropertyChanged("IsNormal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DiagnoseComment {
            get {
                return this.diagnoseCommentField;
            }
            set {
                this.diagnoseCommentField = value;
                this.RaisePropertyChanged("DiagnoseComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DocFani_ID {
            get {
                return this.docFani_IDField;
            }
            set {
                this.docFani_IDField = value;
                this.RaisePropertyChanged("DocFani_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] lstDiagnoseCode {
            get {
                return this.lstDiagnoseCodeField;
            }
            set {
                this.lstDiagnoseCodeField = value;
                this.RaisePropertyChanged("lstDiagnoseCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_Request_Eprsc", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_Request_EprscRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ParTest4.TaminServices.ParaUserInfo ParaUInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ParTest4.TaminServices.EPrescInfo EPrcInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public ParTest4.TaminServices.LabPrescInfo LabPrscInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public ParTest4.TaminServices.PhysioPrescInfo PhyPrscInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public ParTest4.TaminServices.PrescDInfo[] PrescDInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string logMessage;
        
        public Save_Request_EprscRequest() {
        }
        
        public Save_Request_EprscRequest(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.EPrescInfo EPrcInfo, ParTest4.TaminServices.LabPrescInfo LabPrscInfo, ParTest4.TaminServices.PhysioPrescInfo PhyPrscInfo, ParTest4.TaminServices.PrescDInfo[] PrescDInfo, string logMessage) {
            this.ParaUInfo = ParaUInfo;
            this.EPrcInfo = EPrcInfo;
            this.LabPrscInfo = LabPrscInfo;
            this.PhyPrscInfo = PhyPrscInfo;
            this.PrescDInfo = PrescDInfo;
            this.logMessage = logMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Save_Request_EprscResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Save_Request_EprscResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ParTest4.TaminServices.Result_Para Save_Request_EprscResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string logMessage;
        
        public Save_Request_EprscResponse() {
        }
        
        public Save_Request_EprscResponse(ParTest4.TaminServices.Result_Para Save_Request_EprscResult, string logMessage) {
            this.Save_Request_EprscResult = Save_Request_EprscResult;
            this.logMessage = logMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ParaclinicWebServiceSoapChannel : ParTest4.TaminServices.ParaclinicWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParaclinicWebServiceSoapClient : System.ServiceModel.ClientBase<ParTest4.TaminServices.ParaclinicWebServiceSoap>, ParTest4.TaminServices.ParaclinicWebServiceSoap {
        
        public ParaclinicWebServiceSoapClient() {
        }
        
        public ParaclinicWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParaclinicWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParaclinicWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParaclinicWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ParTest4.TaminServices.Result_Para Save_Diagnose_par(ParTest4.TaminServices.ParaUserInfo ParaUInfo, long sRequestId, ParTest4.TaminServices.Diagnose Diagno) {
            return base.Channel.Save_Diagnose_par(ParaUInfo, sRequestId, Diagno);
        }
        
        public System.Threading.Tasks.Task<ParTest4.TaminServices.Result_Para> Save_Diagnose_parAsync(ParTest4.TaminServices.ParaUserInfo ParaUInfo, long sRequestId, ParTest4.TaminServices.Diagnose Diagno) {
            return base.Channel.Save_Diagnose_parAsync(ParaUInfo, sRequestId, Diagno);
        }
        
        public ParTest4.TaminServices.Result_Para Save_Session_physio(ParTest4.TaminServices.ParaUserInfo ParaUInfo, long sRequestId, System.Data.DataTable sParList, string sParListJson) {
            return base.Channel.Save_Session_physio(ParaUInfo, sRequestId, sParList, sParListJson);
        }
        
        public System.Threading.Tasks.Task<ParTest4.TaminServices.Result_Para> Save_Session_physioAsync(ParTest4.TaminServices.ParaUserInfo ParaUInfo, long sRequestId, System.Data.DataTable sParList, string sParListJson) {
            return base.Channel.Save_Session_physioAsync(ParaUInfo, sRequestId, sParList, sParListJson);
        }
        
        public ParTest4.TaminServices.Result_Para Save_Request(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.DoctorInfo DocInfo, ParTest4.TaminServices.PrescInfo PrcInfo, ParTest4.TaminServices.LabPrescInfo LabPrscInfo, ParTest4.TaminServices.PhysioPrescInfo PhyPrscInfo, ParTest4.TaminServices.PrescDInfo[] PrescDInfo) {
            return base.Channel.Save_Request(ParaUInfo, DocInfo, PrcInfo, LabPrscInfo, PhyPrscInfo, PrescDInfo);
        }
        
        public System.Threading.Tasks.Task<ParTest4.TaminServices.Result_Para> Save_RequestAsync(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.DoctorInfo DocInfo, ParTest4.TaminServices.PrescInfo PrcInfo, ParTest4.TaminServices.LabPrescInfo LabPrscInfo, ParTest4.TaminServices.PhysioPrescInfo PhyPrscInfo, ParTest4.TaminServices.PrescDInfo[] PrescDInfo) {
            return base.Channel.Save_RequestAsync(ParaUInfo, DocInfo, PrcInfo, LabPrscInfo, PhyPrscInfo, PrescDInfo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ParTest4.TaminServices.Save_Request_EprscResponse ParTest4.TaminServices.ParaclinicWebServiceSoap.Save_Request_Eprsc(ParTest4.TaminServices.Save_Request_EprscRequest request) {
            return base.Channel.Save_Request_Eprsc(request);
        }
        
        public ParTest4.TaminServices.Result_Para Save_Request_Eprsc(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.EPrescInfo EPrcInfo, ParTest4.TaminServices.LabPrescInfo LabPrscInfo, ParTest4.TaminServices.PhysioPrescInfo PhyPrscInfo, ParTest4.TaminServices.PrescDInfo[] PrescDInfo, ref string logMessage) {
            ParTest4.TaminServices.Save_Request_EprscRequest inValue = new ParTest4.TaminServices.Save_Request_EprscRequest();
            inValue.ParaUInfo = ParaUInfo;
            inValue.EPrcInfo = EPrcInfo;
            inValue.LabPrscInfo = LabPrscInfo;
            inValue.PhyPrscInfo = PhyPrscInfo;
            inValue.PrescDInfo = PrescDInfo;
            inValue.logMessage = logMessage;
            ParTest4.TaminServices.Save_Request_EprscResponse retVal = ((ParTest4.TaminServices.ParaclinicWebServiceSoap)(this)).Save_Request_Eprsc(inValue);
            logMessage = retVal.logMessage;
            return retVal.Save_Request_EprscResult;
        }
        
        public System.Threading.Tasks.Task<ParTest4.TaminServices.Save_Request_EprscResponse> Save_Request_EprscAsync(ParTest4.TaminServices.Save_Request_EprscRequest request) {
            return base.Channel.Save_Request_EprscAsync(request);
        }
        
        public ParTest4.TaminServices.Result_Para Delete_Request_Eprsc(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.EPrescInfo EPrcInfo) {
            return base.Channel.Delete_Request_Eprsc(ParaUInfo, EPrcInfo);
        }
        
        public System.Threading.Tasks.Task<ParTest4.TaminServices.Result_Para> Delete_Request_EprscAsync(ParTest4.TaminServices.ParaUserInfo ParaUInfo, ParTest4.TaminServices.EPrescInfo EPrcInfo) {
            return base.Channel.Delete_Request_EprscAsync(ParaUInfo, EPrcInfo);
        }
    }
}
